version: '2'
services:
    wwwserver:
       build: .
       image: dasn/nodewebapp 
       environment:
            PORT: 3000 
       ports:
            - "8080:3000"
       volumes:
            - ./src:/app
       entrypoint: bash -c "rm -fr node_modules ; npm install ; node app.js "
